main: com.gokborg.gokplugin.GokPlugin
name: GokPlugin
version: 0.06
author: Gokborg
commands:
  ifloss:
    description: It checks if you floss.
    usage: /ifloss
    permission: gokplugin.permission
  up:
    description: It places a block beneath you.
    usage: /up
    permission: gokplugin.permission
  ss:
    description: Gives you a wand to detect SS.
    usage: /ss
    permission: gokplugin.permission
  fill:
    description: Fills a selection.
    usage: /fill 
    permission: gokplugin.permission
  copy:
    description: Copies a selection.
    usage: /copy
    permission: gokplugin.permission
  paste:
    description: Paste a selection.
    usage: /paste
    permission: gokplugin.permission
  replace:
    description: Replaces one block type with another.
    usage: /replace
    permission: gokplugin.permission
  undo:
    description: Undo's a edit operation
    usage: /undo
    permission: gokplugin.permission    